### ISSUE TITLE
Migration to aioredis 2.0.0

### ISSUE THREAD

**Issue by mariaines** [DriverX/aioredis-cluster#3]
Hi, are there any plans to [migrate to aioredis 2.0.0](https://aioredis.readthedocs.io/en/latest/migration/)? 

I am running into occasional ConnectionResetError and [this issue](https://github.com/aio-libs/aioredis-py/issues/778) suggests 2.0.0 might fix it (maybe...)

**Comment by Tiergarten** [comment]
+1

@mariaines How did you end up proceeding? redis-py-cluster looks like a potential alternative but its not asyncio.

**Comment by DriverX** [comment]
Are you sure the problem is with aioredis and not with the number of connections on redis node? Check `connected_clients` and `rejected_connections` in `INFO` command output. Also check `maxclients` config option if `connected_clients` near on this limit. Also make sure you have enough network resources (number of ports, limits, TCP_NOWAIT states, etc.) on the client host and redis itself.

ConnectionResetError usually means network level problems. this is in fact receive of the RST packet.

**Comment by DriverX** [comment]
And answer the question. There are no plans to migrate to `aioredis>=2`.
